  name: Eleventy generator action
  # You may pin to the exact commit or the version.
  # uses: maschmann/eleventy-build-action@b26bf76e8e0d693b1024c80de3f8cd4c247011bd
  uses: maschmann/eleventy-build-action@v1.0.5
  with:
    # The version of Node.js to install.
    node_version: # default is 23
    # The working directory to use.
    working_directory: # optional, default is .
    # Optional: Specify the output directory for Eleventy.
    output: # optional
    # Optional: Run Eleventy in quiet mode.
    quiet: # optional
